### ISSUE TITLE
Throw and exception when inferring from JSON Schema and the resulting Concerto is about to include reserved keywords

### ISSUE THREAD

**Issue by stefanblaginov** [accordproject/concerto-codegen#48]
## Context

Concerto has [a number of reserved words that cannot be used in a valid Concerto file](https://github.com/accordproject/concerto/blob/51dc8eb141ebb142b6964a25830fdeb21e147909/packages/concerto-core/lib/modelutil.js#L23C1-L51C21). Currently the JSON Schema inference code lets us create a Concerto file with these reserved words.

That should not be the case and and error must be thrown that an invalid file is about be created.

**Comment by kailash360** [comment]
@stefanblaginov 

Can I take up this issue?

**Comment by sanketshevkar** [comment]
Yep sure!

**Comment by kailash360** [comment]
Since we already have the list of available reserved words, we can check if the current field is a part of the list or not. However, I have small doubt if we should check for these words without the `$` symbol as well. For example, if `$timestamp` is a reserved word then user obviously cannot use `$timestamp` in the concerto file, but whether the user can use `timestamp` field or not.

@sanketshevkar can you please confirm on this?

**Comment by sanketshevkar** [comment]
> Since we already have the list of available reserved words, we can check if the current field is a part of the list or not. However, I have small doubt if we should check for these words without the `$` symbol as well. For example, if `$timestamp` is a reserved word then user obviously cannot use `$timestamp` in the concerto file, but whether the user can use `timestamp` field or not.

I believe `$` is added so as to let users know its a reserved keyword. We would like to name our variables like `$class` or `__prototype__` (in JS), so that someone won't accidently use them. @dselman is that correct?
